-- -- ===========================================
-- --  FULL CONSTRUCTION COMPANY DATABASE SCHEMA
-- --  WITH INVESTORS, LOANS & EXPENSE TRACKING
-- -- ===========================================

-- -- USER TYPES (Admin, Manager, Employee, etc.)
-- CREATE TABLE user_types (
--     user_type_id INT AUTO_INCREMENT PRIMARY KEY,
--     user_type_name VARCHAR(50) NOT NULL
-- );

-- -- USERS (Admin, Employees, etc.)
-- CREATE TABLE users (
--     user_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100),
--     email VARCHAR(100) UNIQUE,
--     password VARCHAR(255),
--     phone VARCHAR(50),
--     user_type_id INT,
--     FOREIGN KEY (user_type_id) REFERENCES user_types(user_type_id)
-- );

-- -- DEPARTMENTS
-- CREATE TABLE departments (
--     dept_id INT AUTO_INCREMENT PRIMARY KEY,
--     dept_name VARCHAR(100),
--     user_type_id INT,
--     FOREIGN KEY (user_type_id) REFERENCES user_types(user_type_id)
-- );

-- -- DESIGNATIONS / DESTINATIONS
-- CREATE TABLE designations (
--     dest_id INT AUTO_INCREMENT PRIMARY KEY,
--     dest_name VARCHAR(100),
--     user_type_id INT,
--     FOREIGN KEY (user_type_id) REFERENCES user_types(user_type_id)
-- );

-- -- EMPLOYEES
-- CREATE TABLE employees (
--     emp_id INT AUTO_INCREMENT PRIMARY KEY,
--     first_name VARCHAR(100),
--     last_name VARCHAR(100),
--     cnic VARCHAR(20) UNIQUE,
--     phone VARCHAR(50),
--     email VARCHAR(100),
--     hire_date DATE,
--     salary DECIMAL(12,2),
--     dept_id INT,
--     dest_id INT,
--     FOREIGN KEY (dept_id) REFERENCES departments(dept_id),
--     FOREIGN KEY (dest_id) REFERENCES designations(dest_id)
-- );

-- -- CLIENTS
-- CREATE TABLE clients (
--     client_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100),
--     contact_person VARCHAR(100),
--     phone VARCHAR(50),
--     email VARCHAR(100),
--     address TEXT
-- );

-- -- PROJECTS
-- CREATE TABLE projects (
--     pro_id INT AUTO_INCREMENT PRIMARY KEY,
--     title VARCHAR(100),
--     description TEXT,
--     location VARCHAR(150),
--     start_date DATE,
--     end_date DATE,
--     estimated_budget DECIMAL(14,2),
--     actual_cost DECIMAL(14,2) DEFAULT 0,
--     status VARCHAR(50),
--     client_id INT,
--     manager_id INT,
--     FOREIGN KEY (client_id) REFERENCES clients(client_id),
--     FOREIGN KEY (manager_id) REFERENCES employees(emp_id)
-- );

-- -- PROJECT TASKS
-- CREATE TABLE tasks (
--     task_id INT AUTO_INCREMENT PRIMARY KEY,
--     task_name VARCHAR(100),
--     task_description TEXT,
--     start_date DATE,
--     end_date DATE,
--     status VARCHAR(50),
--     pro_id INT,
--     emp_id INT,
--     FOREIGN KEY (pro_id) REFERENCES projects(pro_id),
--     FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
-- );

-- -- ATTENDANCE
-- CREATE TABLE attendance (
--     att_id INT AUTO_INCREMENT PRIMARY KEY,
--     emp_id INT,
--     att_date DATE,
--     status ENUM('Present','Absent','Leave'),
--     FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
-- );

-- -- SALARY RECORDS
-- CREATE TABLE salary_records (
--     sal_id INT AUTO_INCREMENT PRIMARY KEY,
--     emp_id INT,
--     month VARCHAR(20),
--     total_days INT,
--     present_days INT,
--     gross_amount DECIMAL(12,2),
--     status ENUM('Paid','Unpaid') DEFAULT 'Unpaid',
--     FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
-- );

-- -- SUPPLIERS
-- CREATE TABLE suppliers (
--     sup_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100),
--     contact VARCHAR(50),
--     address TEXT
-- );

-- -- MATERIALS
-- CREATE TABLE materials (
--     material_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100),
--     description TEXT,
--     unit_price DECIMAL(12,2),
--     supplier_id INT,
--     FOREIGN KEY (supplier_id) REFERENCES suppliers(sup_id)
-- );

-- -- PROJECT MATERIALS (usage)
-- CREATE TABLE project_materials (
--     pro_id INT,
--     material_id INT,
--     quantity INT,
--     total_cost DECIMAL(14,2),
--     PRIMARY KEY (pro_id, material_id),
--     FOREIGN KEY (pro_id) REFERENCES projects(pro_id),
--     FOREIGN KEY (material_id) REFERENCES materials(material_id)
-- );

-- -- INVESTORS
-- CREATE TABLE investors (
--     investor_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100),
--     contact VARCHAR(50),
--     email VARCHAR(100),
--     investment_type ENUM('Equity','Loan'),
--     invested_amount DECIMAL(14,2),
--     investment_date DATE,
--     profit_share_percent DECIMAL(5,2),
--     project_id INT,
--     FOREIGN KEY (project_id) REFERENCES projects(pro_id)
-- );

-- -- BANKS
-- CREATE TABLE banks (
--     bank_id INT AUTO_INCREMENT PRIMARY KEY,
--     bank_name VARCHAR(150),
--     branch VARCHAR(100),
--     account_number VARCHAR(50),
--     ifsc_code VARCHAR(50)
-- );

-- -- LOANS
-- CREATE TABLE loans (
--     loan_id INT AUTO_INCREMENT PRIMARY KEY,
--     loan_type ENUM('Debit','Credit'),
--     amount DECIMAL(14,2),
--     issue_date DATE,
--     due_date DATE,
--     interest_rate DECIMAL(5,2),
--     status ENUM('Ongoing','Completed','Defaulted') DEFAULT 'Ongoing',
--     bank_id INT,
--     project_id INT,
--     FOREIGN KEY (bank_id) REFERENCES banks(bank_id),
--     FOREIGN KEY (project_id) REFERENCES projects(pro_id)
-- );

-- -- TRANSACTIONS (daily / weekly / monthly)
-- CREATE TABLE transactions (
--     transaction_id INT AUTO_INCREMENT PRIMARY KEY,
--     project_id INT,
--     transaction_date DATE,
--     transaction_type ENUM('Income','Expense'),
--     payment_mode ENUM('Cash','Cheque','Debit','Credit','Transfer'),
--     amount DECIMAL(14,2),
--     description TEXT,
--     source VARCHAR(100),
--     FOREIGN KEY (project_id) REFERENCES projects(pro_id)
-- );

-- -- RENTALS (equipment or materials rented)
-- CREATE TABLE rentals (
--     rent_id INT AUTO_INCREMENT PRIMARY KEY,
--     item_name VARCHAR(100),
--     rent_from DATE,
--     rent_to DATE,
--     rent_amount DECIMAL(12,2),
--     supplier_id INT,
--     project_id INT,
--     FOREIGN KEY (supplier_id) REFERENCES suppliers(sup_id),
--     FOREIGN KEY (project_id) REFERENCES projects(pro_id)
-- );

-- -- EXPENSE TRACKING BY PERIOD
-- CREATE TABLE expense_reports (
--     report_id INT AUTO_INCREMENT PRIMARY KEY,
--     project_id INT,
--     period_type ENUM('Daily','Weekly','Monthly'),
--     start_date DATE,
--     end_date DATE,
--     total_income DECIMAL(14,2),
--     total_expense DECIMAL(14,2),
--     net_profit DECIMAL(14,2),
--     FOREIGN KEY (project_id) REFERENCES projects(pro_id)
-- );

-- -- ===========================================
-- --  SUPPORT & RELATIONAL TABLES (REMAINING 7)
-- -- ===========================================

-- -- 1️⃣ PROJECT EQUIPMENT (which equipment used in which project)
-- CREATE TABLE project_equipment (
--     pro_id INT,
--     equip_id INT,
--     usage_start_date DATE,
--     usage_end_date DATE,
--     total_cost DECIMAL(12,2),
--     PRIMARY KEY (pro_id, equip_id),
--     FOREIGN KEY (pro_id) REFERENCES projects(pro_id),
--     FOREIGN KEY (equip_id) REFERENCES equipment(equip_id)
-- );

-- -- 2️⃣ EQUIPMENT MASTER TABLE
-- CREATE TABLE equipment (
--     equip_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100),
--     type VARCHAR(100),
--     purchase_date DATE,
--     price DECIMAL(12,2),
--     condition_status ENUM('Available','In Use','Maintenance') DEFAULT 'Available',
--     location VARCHAR(100)
-- );

-- -- 3️⃣ PROJECT SUBCONTRACTORS (external partners)
-- CREATE TABLE subcontractors (
--     sub_id INT AUTO_INCREMENT PRIMARY KEY,
--     company_name VARCHAR(150),
--     contact_person VARCHAR(100),
--     phone VARCHAR(50),
--     email VARCHAR(100),
--     specialization VARCHAR(100),
--     address TEXT
-- );

-- CREATE TABLE project_subcontractors (
--     pro_id INT,
--     sub_id INT,
--     contract_amount DECIMAL(14,2),
--     start_date DATE,
--     end_date DATE,
--     PRIMARY KEY (pro_id, sub_id),
--     FOREIGN KEY (pro_id) REFERENCES projects(pro_id),
--     FOREIGN KEY (sub_id) REFERENCES subcontractors(sub_id)
-- );

-- -- 4️⃣ PROJECT DOCUMENTS (like blueprints, permits, reports)
-- CREATE TABLE project_documents (
--     document_id INT AUTO_INCREMENT PRIMARY KEY,
--     pro_id INT,
--     document_name VARCHAR(150),
--     document_type VARCHAR(100),
--     upload_date DATE,
--     file_path VARCHAR(255),
--     FOREIGN KEY (pro_id) REFERENCES projects(pro_id)
-- );

-- -- 5️⃣ NOTIFICATIONS / ALERTS (for system events)
-- CREATE TABLE notifications (
--     notify_id INT AUTO_INCREMENT PRIMARY KEY,
--     user_id INT,
--     message TEXT,
--     notify_type ENUM('Info','Warning','Error','Reminder') DEFAULT 'Info',
--     is_read BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES users(user_id)
-- );

-- -- 6️⃣ ACTIVITY LOGS (system auditing)
-- CREATE TABLE activity_logs (
--     log_id INT AUTO_INCREMENT PRIMARY KEY,
--     user_id INT,
--     action VARCHAR(150),
--     description TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES users(user_id)
-- );

-- -- 7️⃣ SETTINGS / CONFIGURATIONS (company-level preferences)
-- CREATE TABLE settings (
--     setting_id INT AUTO_INCREMENT PRIMARY KEY,
--     setting_key VARCHAR(100),
--     setting_value TEXT
-- );

-- /**
-- **
-- **   last finalize tables of database
-- **
-- **/
